sudo: required
services:
  - docker

before_install:
  - docker build -t arjaydevops/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arjaydevops/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "aws-docker"
  env: "Aws-docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-129350621020"
  bucket_path: "aws-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"